In [65]:
import numpy as np
import matplotlib.pyplot as plt
from pyhdf.SD import SD, SDC
import glob
from datetime import datetime, date, timedelta

datadir='/data/keeling/a/yulanh/c/BW_backup/output/'

fnames=glob.glob(datadir+'*201908*')
minlat=30
maxlat=45
minlon=-140
maxlon=-125
fnames=fnames[0:10]

for fname in fnames:
    if len(fname) == 88:
        print(fname)
        hdf=SD(fname)
        lat=hdf.select('latitude')[:]
        lon=hdf.select('longitude')[:]
        aeroonly_tau=hdf.select('aero_only_tau')[:]
        aeroonly_num=hdf.select('aero_only_numh')[:]
        isolate_tau =hdf.select('isolate_aero_tau')[:]
        isolate_num =hdf.select('isolate_aero_numh')[:]
        connect_tau =hdf.select('incld_aero_tau')[:]
        connect_num =hdf.select('incld_aero_numh')[:]
        lonind=np.where((lon >= minlon) & (lon <=maxlon))[0]
        latind=np.where((lat >= minlat) & (lat <=maxlat))[0]
        
        tpaeroonly_num=aeroonly_num[latind[0]:latind[len(latind)-1]+1,lonind[0]:lonind[len(lonind)-1]+1]
        tpaeroonly_tau=aeroonly_tau[latind[0]:latind[len(latind)-1]+1,lonind[0]:lonind[len(lonind)-1]+1]
        aeroonly_avetau=np.sum(tpaeroonly_tau*tpaeroonly_num)/np.sum(tpaeroonly_num)
        print((tpaeroonly_tau))
        print(tpaeroonly_num)
        print(tpaeroonly_num.shape,'clr ave tau',aeroonly_avetau,'clr num',np.sum(tpaeroonly_num))
        print(connect_num.shape, lonind.shape,latind.shape)
        print(lat[latind])
        print(lon[lonind])

/data/keeling/a/yulanh/c/BW_backup/output/caliop_cldclimatology_cad20_aerocld_201908.hdf
[[0.04226725 0.06632344 0.06031948]
 [0.0583825  0.05954317 0.05893633]
 [0.07600869 0.05619035 0.06154834]
 [0.09053943 0.0739283  0.05585335]]
[[411 347 217]
 [229 497 303]
 [264 335 499]
 [146 318 286]]
(4, 3) clr ave tau 0.061422730630664064 clr num 3852
(6, 36, 60) (3,) (4,)
[30. 35. 40. 45.]
[-138. -132. -126.]
